version: '3.8'

services:
  # 1. Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: barbearia_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 889447Gus
      MYSQL_DATABASE: barbearia_db
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql 
  # 2. API (Back-end)
  api:
    build: ./barbearia-api
    container_name: barbearia_api_container
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - db
    environment:
      # IMPORTANTE: No Docker, o host é o nome do serviço ('db'), não localhost
      DATABASE_URL: mysql://root:889447Gus@db:3306/barbearia_db
      API_PORT: 3333
    volumes:
      - ./barbearia-api:/app
      - /app/node_modules

  # 3. Frontend (Site)
  frontend:
    build: ./barbearia-frontend
    container_name: barbearia_frontend_container
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./barbearia-frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  mysql_data: